version: '3.8'
name: champions_league
services:

  db:
    image: inf25dw1g05/champions_league_db_m3:1.0.0
    container_name: Champions_League-db
    restart: always
    volumes:
      - mysql-data:/var/lib/mysql
    ports:
      - '3306:3306'
  api:
    container_name: Champions_League-api
    restart: always
    image: inf25dw1g05/champions_league_app_m3:1.0.0
    ports:
      - '3000:3000'
    depends_on:
      - db
  backoffice:
    container_name: Champions_League-backoffice
    restart: always
    image: inf25dw1g05/champions_league_react_m3:1.0.0
    ports:
      - '3006:3006'
    depends_on:
      - db
volumes:
  mysql-data: